version: "3"

services:
  postgres:
    image: docker.io/postgres:17
    environment:
      POSTGRES_DB: hello
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
